#!/bin/sh

## Taken from RcppArmadillo
## rm -f  config.log config.status confdefs.h \
##        src/*.o src/*.so \
##        inst/doc/RcppArmadillo-unitTests.out \
##        inst/doc/RcppArmadillo-unitTests.aux \
##        inst/doc/RcppArmadillo-unitTests.log \
##        */*~ *~
## rm -rf autom4te.cache

rm -rf src-*
rm -rf src/*.o src/*.so

for o in `find inst/include/libshogun -name "*.o"`; do rm $o; done

