#!/bin/sh

## Taken from RcppArmadillo
## rm -f  config.log config.status confdefs.h \
##        src/*.o src/*.so \
##        inst/doc/RcppArmadillo-unitTests.out \
##        inst/doc/RcppArmadillo-unitTests.aux \
##        inst/doc/RcppArmadillo-unitTests.log \
##        */*~ *~
## rm -rf autom4te.cache

## Remove compiled C/C++ stuffs
for o in `find src -name "*.o"`; do rm $o; done
for o in `find inst/include -name "*.o"`; do rm $o; done
rm -rf src-*
rm src/*.so

rm src/.depend
